# SPDX-FileCopyrightText: Copyright DB InfraGO AG and contributors
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "Polarion DBS Project Template"
SPDX-PackageSupplier = "Ernst Würger <ernst.wuerger@deutschebahn.com>"
SPDX-PackageDownloadLocation = "https://github.com/DSD-DBS/capella-polarion-template"

[[annotations]]
path = "template/.polarion/icons/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "THALES GLOBAL SERVICES"
SPDX-License-Identifier = "EPL-2.0"

[[annotations]]
path = "global/icons/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "THALES GLOBAL SERVICES"
SPDX-License-Identifier = "EPL-2.0"
