# SPDX-FileCopyrightText: Copyright DB Netz AG and contributors
# SPDX-License-Identifier: CC0-1.0

name: Zip and Publish Template

on:
  release:
    types:
      - created

jobs:
  publish-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Zip Template Folder
      run: |
        mkdir ${{ vars.TEMPLATE_FILENAME }} && cp -r template/. ${{ vars.TEMPLATE_FILENAME }}
        zip -r ${{ vars.TEMPLATE_FILENAME }}.zip ${{ vars.TEMPLATE_FILENAME }}
    - name: Attach ZIP file to release
      uses: shogo82148/actions-upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ vars.TEMPLATE_FILENAME }}.zip
        asset_name: ${{ vars.TEMPLATE_FILENAME }}.zip
        asset_content_type: application/zip
